# keyboard name
CONFIG_ZMK_KEYBOARD_NAME="CORNE_V3"

# Enable eager debouncing
CONFIG_ZMK_KSCAN_DEBOUNCE_PRESS_MS=1
CONFIG_ZMK_KSCAN_DEBOUNCE_RELEASE_MS=5

#explicitly disable sleep
CONFIG_ZMK_SLEEP=n

# 30 minutes (1*30*60*1000ms)
#CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=1800000
# 1 hour (1*60*60*1000ms)
#CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=3600000

# boost BT signal
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y

# enable NKRO
CONFIG_ZMK_HID_REPORT_TYPE_NKRO=y

# enable boot time keyboard usage
CONFIG_ZMK_USB_BOOT=y

# enable Mouse keys
CONFIG_ZMK_MOUSE=y

# custom GEM screen
CONFIG_ZMK_DISPLAY=y
CONFIG_ZMK_DISPLAY_STATUS_SCREEN_CUSTOM=y
CONFIG_NICE_VIEW_GEM_ANIMATION_MS=3840

# Turn on logging, and set ZMK logging to debug output
# CONFIG_ZMK_USB_LOGGING=n
# CONFIG_ZMK_HID_CONSUMER_REPORT_USAGES_BASIC=y

# Enable 32kHz crystal
CONFIG_CLOCK_CONTROL_NRF_K32SRC_XTAL=y
CONFIG_CLOCK_CONTROL_NRF_K32SRC_30PPM=y
